node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('tag') {

     withCredentials([usernamePassword(credentialsId: 'f1468e48-705e-4eaf-8246-412a25597f4a', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
       pushUrl = "https://${PASSWORD}@github.com/ksexton/docker-demo.git"
       sh """
git config --local user.name 'jenkins-ci'
git config --local user.email 'jenkins-ci@sightmachine.com'
git tag -a $(date +%s) -m 'Jenkins'
git push ${pushUrl} --tags
       """
       // sh "git push https://${PASSWORD}@https://github.com/ksexton/docker-demo.git --tags"
       // sh("printenv")       
     }
   }
   // stage('docker build/push') {
   //   docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
   //     def app = docker.build("kylesexton/docker-nodejs-demo:${commit_id}", '.').push()
   //   }
   // }
}
